// Grace Laboratory - Default Master Configuration Data
var DEFAULT_DOCTOR_CUTS = window.DEFAULT_DOCTOR_CUTS = {
  "AARYA WOMEN'S & CHILDREN'S HOSPITAL": 40.0,
  "Aakash Panchal": 0.0,
  "AARZU PARMAR": 30.0,
  "Abhinam Patel": 0.0,
  "Aastha General Hospital": 45.0,
  "Aditi tripathi": 40.0,
  "Abhishek Sharma": 50.0,
  "Aditya Shah": 0.0,
  "Ajay Patel": 50.0,
  "Ajay Baxi": 0.0,
  "AJAY SONI": 40.0,
  "AJAY KESARKAR": 0.0,
  "Akshar Hospital Por": 50.0,
  "AVNI MORZARIA": 0.0,
  "AMIT PANCHAL": 40.0,
  "Ajit B Vaghela": 0.0,
  "ANITA SINGH  DABHOI": 40.0,
  "Akanksha Kothari": 0.0,
  "ankur udwani": 45.0,
  "Akash Singh": 0.0,
  "APEKSHA SHUKALA": 40.0,
  "AKSHAR  CLINIC": 0.0,
  "ashish brambhatt": 45.0,
  "Alpana Gohil": 0.0,
  "ASHIT SHAH": 50.0,
  "AMBAR  LIMAYE": 0.0,
  "BHARGAV SHUKALA": 40.0,
  "Amit Patel": 0.0,
  "BHASKAR SWAMINATHAN IYER": 30.0,
  "Anand Naregal": 0.0,
  "BHAVIK THAKKAR": 50.0,
  "Anil R Dua": 0.0,
  "BHAVIKA PATEL": 40.0,
  "Anil Ganju": 0.0,
  "BHAVIN R. SHAH": 55.0,
  "Anil Shah": 0.0,
  "BHUMI HOSPITAL": 25.0,
  "Anisha Arora Sharma": 0.0,
  "Bipin Prajapati": 40.0,
  "ANKIT DESAI": 0.0,
  "BRIJESH PATEL(4000) EXTRA SALARY": 50.0,
  "Ankit Patel": 0.0,
  "C.M KULKARNI": 40.0,
  "Ankita Khandelwal": 0.0,
  "C.M. Chotalya": 50.0,
  "Ankur Kothari": 0.0,
  "Chaitanya L. Joshi": 40.0,
  "ANKUR SHAKYA": 0.0,
  "CHINTAN THAKKAR": 40.0,
  "Anuj Garg": 0.0,
  "DEEPA JAYSINGANI": 45.0,
  "Ashish M Shah": 0.0,
  "Devangi Dave": 50.0,
  "Ashit K Mehta": 0.0,
  "dhanusha Shah": 0.0,
  "Ashit Vyas": 0.0,
  "Dharmendra Pokkar": 50.0,
  "Ashok Prajapati": 0.0,
  "DHRUVIN PATEL": 40.0,
  "Ashvin Shah": 0.0,
  "Dipti Patel": 40.0,
  "Ashwin G parmar": 0.0,
  "Divyesh Zinzala": 40.0,
  "Atul Jani": 0.0,
  "GAUTAM AHIRE": 0.0,
  "Bhailal Amin": 0.0,
  "GUNJITA YARDE": 50.0,
  "Bhaktadas Patel": 0.0,
  "Harish Desai": 40.0,
  "BHARGAV  PATEL": 0.0,
  "Harshad Ladumor": 40.0,
  "BHARGAV DAVE": 0.0,
  "Helly Desai": 40.0,
  "Bhavesh Patel": 0.0,
  "HEMAL S PARIKH": 45.0,
  "Bhavik K soni": 0.0,
  "HETAL KATHrotia": 30.0,
  "Bhavin C Shah": 0.0,
  "Hetal Kathrotiya": 30.0,
  "Bhavin Soni": 0.0,
  "Hetal Vaidya": 40.0,
  "BHUMIK ACHARY": 0.0,
  "Bibhas Shah": 0.0,
  "Himanshu Panchal": 50.0,
  "Chetan Trivedi": 0.0,
  "HIREN CHAUDARI": 40.0,
  "Chetan Vishpute": 0.0,
  "HIREN K.SONI": 40.0,
  "CHINMAY JOSHI": 0.0,
  "HITESH BHALERA": 50.0,
  "Chirag H Patel": 0.0,
  "Hitesh Prajapati": 0.0,
  "Chirag Rathod": 0.0,
  "HRUTVIK THAKkaR": 35.0,
  "Chetan Janduani": 0.0,
  "Javed Nakum": 50.0,
  "Darshan Patel": 0.0,
  "JAYESH PRAJAPTI": 50.0,
  "Daxesh Panchal": 0.0,
  "jaykrushna mekhia": 60.0,
  "DEEPAK SHAH": 0.0,
  "JAYVIRSINH JADEJA": 50.0,
  "Dharmesh Dhamat": 0.0,
  "jayvirsinh jadeja": 50.0,
  "DHARMESH PATEL": 0.0,
  "jimit Desai": 50.0,
  "Dhaval P Sheth": 0.0,
  "jinesh shah": 40.0,
  "Dhrumil Soni": 0.0,
  "karishma matai": 40.0,
  "Dilita Bhagade": 0.0,
  "Krishna Children and dental Hospital ( Dr. Rachit Shah)": 50.0,
  "Dishank Patel": 0.0,
  "KRUTESH SHAH": 50.0,
  "DIVYANG KADAKIYA": 0.0,
  "LOPA RANA": 40.0,
  "Divyesh Parmar": 0.0,
  "MADHU BHASKAR IYER": 30.0,
  "Dovyesh Parmar": 0.0,
  "Manoj Mehta": 45.0,
  "Dushyant J Bhatt": 0.0,
  "Manoj r Mehta": 60.0,
  "ESHA PATEL": 0.0,
  "Mihir Patel": 40.0,
  "GAURANG G.  PATEL": 0.0,
  "MILAN G. PANCHAL": 40.0,
  "Gopal Shah": 0.0,
  "Mitali Shah": 0.0,
  "GUNJAN A PATEL": 0.0,
  "n k mishra": 60.0,
  "H C G Hospital": 0.0,
  "N S INGLE": 40.0,
  "Hardik dave": 0.0,
  "NAINESH SHAH": 40.0,
  "Hardik Varia": 0.0,
  "NANAK JAYSINGANI": 45.0,
  "Haresh Shah": 0.0,
  "NARESH PATEL": 30.0,
  "Harish Patel": 0.0,
  "NEERAJ MAHESWARI": 40.0,
  "Ankur Prajapati": 0.0,
  "Neeta Rangwani": 40.0,
  "Harshal Joshi": 0.0,
  "NIKUNJ B MANVAR": 45.0,
  "Harshil Shah": 0.0,
  "Nil Patel": 50.0,
  "Hemang Vaid": 0.0,
  "Nitin Shah": 40.0,
  "Hemant Patel": 0.0,
  "PADAM GUPTA": 40.0,
  "Himanshu Trivedi": 0.0,
  "PANKAJ GUPTA": 40.0,
  "Jagruti Patel": 0.0,
  "Pankaj Hadiya": 40.0,
  "JAIMIN R SHAH": 0.0,
  "PARTH JOSHI": 50.0,
  "Jalpa Dave": 0.0,
  "PARUL H.SONI": 40.0,
  "Janardhan Dave": 0.0,
  "PINAL P ROKADE": 40.0,
  "Jayant Acharya": 0.0,
  "Pooja N parikh": 50.0,
  "JAYPRAKASH A Purohit": 0.0,
  "PRADEEP R. NAIK": 50.0,
  "11": 0.0,
  "Prafullata Patel": 40.0,
  "Jeet Patel": 0.0,
  "PRAGNESH SHUKLA": 40.0,
  "JIGAR C BHAVSAR": 0.0,
  "prakash dasa": 60.0,
  "JIGAR J PATEL": 0.0,
  "prakash v Patel": 50.0,
  "Jigar Mehta": 0.0,
  "Pratibha Gupta": 40.0,
  "Jigar Parikh": 0.0,
  "pratima gandhi": 40.0,
  "Jigen Shah": 0.0,
  "PRAVEEN BHIDE": 50.0,
  "Jignesh Parikh": 0.0,
  "priya jatin shah": 45.0,
  "Jignesh Prajapati": 0.0,
  "priyank Trivedi": 45.0,
  "JIGNESH S. PATEL": 0.0,
  "Priyanka Shah": 40.0,
  "Jitendra Desai": 0.0,
  "rachit shah ( krishna Hospital)": 50.0,
  "Jitendra Mistry": 0.0,
  "RAJ  D SHROF": 40.0,
  "K R Buch": 0.0,
  "RAJESH SHAH": 30.0,
  "KAMLESH N. PARIKH": 0.0,
  "Rajiv Jesani": 40.0,
  "Kanta Patel": 0.0,
  "RAKESH B PATEL MANEJA": 40.0,
  "Kanubhai Parmar": 0.0,
  "rakesh K patel": 40.0,
  "Kaushal C Thakkar": 0.0,
  "RAMESH DUBE": 50.0,
  "Kaushik Trivedi": 0.0,
  "RAMYA MAHESHWARI": 40.0,
  "Kedar Suthar": 0.0,
  "Reena B Choksi": 40.0,
  "Ketan Prajapati": 0.0,
  "robin singh": 50.0,
  "Keyur Shah": 0.0,
  "ruchit patel": 45.0,
  "Kiran Shah (pooja nursing home)": 0.0,
  "Ruchit Shah": 50.0,
  "Kishan Jani": 0.0,
  "Rushita Om Clinic Makarpura": 50.0,
  "Krishna Dave Vaidya": 0.0,
  "SANDEEP SHAH": 25.0,
  "Krishnakant Patel": 0.0,
  "sangeeta Patel": 50.0,
  "Kundan Chaudhary": 0.0,
  "sangita barad": 50.0,
  "LEENA M JAYSINGANIYA": 0.0,
  "SATISH GIRI": 50.0,
  "MAHESH B PATEL": 0.0,
  "seema solanki": 50.0,
  "MAHESH PANDYA": 0.0,
  "SHAILESH CHAVDA": 40.0,
  "Manish Patel": 0.0,
  "SHAILESH RATHOD": 40.0,
  "Manoj Parmar": 0.0,
  "Shailesh Talati": 30.0,
  "Manthan Shah": 0.0,
  "SHILPA CHUDHARI": 40.0,
  "Mayank Chauhan": 0.0,
  "Shubh Shah": 50.0,
  "Meera Desai": 0.0,
  "shweta amin": 50.0,
  "MEHUL C.SHAH": 0.0,
  "SMIT DESAI": 40.0,
  "Mehul Shah": 0.0,
  "Sumit Patel": 40.0,
  "Milan Doshi": 0.0,
  "sunanda Patel": 40.0,
  "Minal Prajapati": 0.0,
  "Sunil Maniyar": 30.0,
  "Ankit A Singhania": 0.0,
  "Sunil Patel": 40.0,
  "Mohit J Shah": 0.0,
  "t": 30.0,
  "Mohit Patel": 0.0,
  "Tanupa Patel": 40.0,
  "MONA SHAH": 0.0,
  "TANVESH PATEL": 50.0,
  "POOJA BELANI BHAILAL AMIN GENERAL HOSPITAL": 0.0,
  "TISHA PATEL": 40.0,
  "d": 0.0,
  "TUSHAR PATEL (sparsh clinic)": 40.0,
  "Nayan baria": 0.0,
  "Umang Joshi": 40.0,
  "NIDHI SAINI": 0.0,
  "umang SOlanki": 50.0,
  "Nilpa B Patel": 0.0,
  "VAKHAT PARMAR": 40.0,
  "NIRAJ BHATT": 0.0,
  "VANDAN H KUMAR": 50.0,
  "NIRAJ D SHAH": 0.0,
  "Ved Hospital (vandan Kumar?)": 50.0,
  "Nisarg Oza": 0.0,
  "VIHANG  PATEL": 0.0,
  "Nisha Pandya": 0.0,
  "Viral Patel": 30.0,
  "NISHIDH PANDYA": 0.0,
  "VIREN PATEL": 50.0,
  "Niyati K Patel": 0.0,
  "vraj hospital": 45.0,
  "PADMAJA J. PEPALLA M.D. (OBS.&GYN)": 0.0,
  "YASH HOSPITAL PADRA": 50.0,
  "PANKAJKUMAR SHARMA": 0.0,
  "VIRENDRASINH": 40.0,
  "PARUL CHAUHAN": 0.0,
  "Pinaki Mahato": 0.0,
  "Priti Niranjan": 40.0,
  "Jayesh j Shah": 0.0,
  "HUZAIFA PATEL": 50.0,
  "Pradip prajapati": 0.0,
  "Mudrik Patel": 45.0,
  "PRAKASH BAGADE": 0.0,
  "Asit Shah": 50.0,
  "Prakash Pathak": 0.0,
  "Pratik J shah": 0.0,
  "PRIYANKA PATEL": 0.0,
  "PRUTHVIRAJ PUWAR": 0.0,
  "R K Sinha": 0.0,
  "RADHIKA PATEL": 0.0,
  "Rahul B Vasava": 0.0,
  "Rajesh Baxi": 0.0,
  "Rajesh H Vyas": 0.0,
  "RAJESH M.RANE": 0.0,
  "Rajiv Pakhetra": 0.0,
  "Rakesh Shah": 0.0,
  "Raman Handa": 0.0,
  "Ramesh Goyal": 0.0,
  "Ramesh Kanani": 0.0,
  "Ranjeet Shukla": 0.0,
  "Ranjit Kadam": 0.0,
  "Raship Patel": 0.0,
  "Ravi Patel": 0.0,
  "Ravi Upadhyay": 0.0,
  "RAVINDRA PRADHAN": 0.0,
  "Ravish Patel": 0.0,
  "REEMA BAXI": 0.0,
  "RIDDHI PATEL": 0.0,
  "RIPAL H SHAH": 0.0,
  "Rishabh Handa": 0.0,
  "Ritu Gupta": 0.0,
  "RONAK RUPARELIA": 0.0,
  "Roopal Panchani": 0.0,
  "Ruchira Agrawal": 0.0,
  "Ruchita Patel": 0.0,
  "Rumin Shah": 0.0,
  "Rupa H Shah": 0.0,
  "S M Patel": 0.0,
  "SAMIR SAINI": 0.0,
  "Sandip Desai": 0.0,
  "SANDIP V MAKWANA": 0.0,
  "SANJAY K.PATEL": 0.0,
  "SANJAY PATEL": 0.0,
  "Sanjay Shah": 0.0,
  "Sanket Saraiya": 0.0,
  "Sarika Jain": 0.0,
  "Sejal Desai": 0.0,
  "SEJAL H CHAVDA": 0.0,
  "Shabbir NANDARVAWALA": 0.0,
  "Hemang H Panchal": 0.0,
  "Shital Vaidya": 0.0,
  "SHRUTI AGRAWAL": 0.0,
  "PRASANNA A LALVANI": 0.0,
  "SMITA SHAH": 0.0,
  "Som J Lakhani": 0.0,
  "Suresh zinjuwaiya": 0.0,
  "Sushma Baxi": 0.0,
  "T J Prajapati": 0.0,
  "Rushabh Somani": 0.0,
  "TEJAS K SHETH ( VEDANT CLINIC )": 0.0,
  "Thakorbhai V patel": 0.0,
  "TRICOLOUR HOSPITAL": 0.0,
  "TRUPAL DESAI": 0.0,
  "TUSHAR  SHAH": 0.0,
  "UMANG  GANDHI": 0.0,
  "Upesh Parmar": 0.0,
  "Urmil Nimkar": 0.0,
  "VAIBHAV PARGHI": 0.0,
  "Valay Jain": 0.0,
  "Vijay Patel (DUP)": 0.0,
  "Meera Shah": 0.0,
  "BIRENROY CHAUHAN": 0.0,
  "Vijay Patel": 0.0,
  "Vilay Jain": 0.0,
  "Vinayak M Pawar": 0.0,
  "VIPUL BHAVSAR": 0.0,
  "Vipul D Vyas": 0.0,
  "Vipul Vaghela": 0.0,
  "VIRENDRA KOSAMIYA": 0.0,
  "Viroc Hospital": 0.0,
  "Vishnu Kumar D Patel": 0.0,
  "XL radiology": 0.0,
  "YOGITA CHAUHAN": 0.0,
  "Yuvrajsinh Jadeja": 0.0,
  "Zydus Hospital": 0.0,
  "Darshan Bankar": 0.0,
  "Bharat Barad": 0.0,
  "Dr. BINA R SHAH": 0.0,
  "Bhikhubhai Patel": 0.0,
  "Kishan N Zinzuwadia": 0.0,
  "Krunal Jadhav": 0.0,
  "Manisha Athale": 0.0,
  "Manish N Naringe": 0.0,
  "V C Chauhan": 0.0,
  "Himanshu Gandhi (madhuram Hospital)": 0.0,
  "Samir J Shah": 0.0,
  "Ratnadip A Chitroda": 0.0,
  "Bhavin Upadhyay": 0.0,
  "Binal H Shah": 0.0,
  "Kiran Maheshwari": 0.0,
  "Mihir Shah": 0.0,
  "Prem Jambucha": 0.0,
  "Ronak R Jadia": 0.0,
  "Rupal Shah": 0.0,
  "Bhavin Patel": 0.0,
  "RITESH SINGH MALIK": 0.0,
  "TYRONE FERNANDES": 0.0,
  "Thakorbhai Bhatt": 0.0,
  "Udai Desai": 0.0,
  "Rajesh H Rana": 0.0,
  "Samir R. Parekh": 0.0,
  "Sushruta Innovations & Wellness Pvt Ltd": 0.0,
  "Chirayu M. Chokshi": 0.0,
  "SANJIV C. SHAH": 0.0,
  "Maulik Panchal": 0.0,
  "Kirti B Amin": 0.0,
  "ZEEL S. TRIPATHI": 0.0,
  "CHINMAYE SAPRE": 0.0,
  "Alpa Shah": 0.0,
  "D.S SUBHEDAR": 0.0,
  "Jasmin Patel": 0.0,
  "Aarti Gohil": 0.0,
  "Naresh Mulchandani": 0.0,
  "R.B BHESANIA": 0.0,
  "SAURABH JAMBU": 0.0,
  "Suchi Doshi": 0.0,
  "DEVANAND S. PANCHAL": 0.0,
  "Arpan Desai": 0.0,
  "STUTI PATEL": 0.0,
  "AFTAB MERCHANT": 0.0,
  "Amit Dave": 0.0,
  "ANANT AGRAWAL": 0.0,
  "DHRUMIL M PATEL": 0.0,
  "Rajesh A. Shrotriya": 0.0,
  "NIRAV N. PANCHANI": 0.0,
  "ADITYA SUDHAKAR": 0.0,
  "Jay Joshi": 0.0,
  "Parthiv Shah": 0.0,
  "Rini Shah": 0.0,
  "RACHISWAYATA GUPTA": 0.0,
  "RAJAT N. KUMAR": 0.0,
  "Renu Pawar": 0.0,
  "Arkesh Shukla": 0.0,
  "Gajera Hardik": 0.0,
  "JHANVI M CHAVDA SARBHAN": 0.0,
  "KALPESH JANI": 0.0,
  "LALIT GRIGLANI": 0.0,
  "Virendrakumar Patel": 0.0,
  "MINAXI PATEL": 0.0,
  "NAREN VEGADA": 0.0,
  "RASESH DESAI": 0.0,
  "Hiren Mehta": 0.0,
  "0": 0.0,
  "DHAVAL VAISHANAV": 0.0,
  "GURUDATT J. PATEL": 0.0,
  "PRADIP DLWADI": 0.0,
  "SHASHIK NAYAK": 0.0,
  "VISHAL RAMESH DEDHIA": 0.0,
  "Mukesh K Shah": 0.0,
  "SUNIL SALAT": 0.0,
  "BHARAT RAMCHANDANI": 0.0,
  "DEEP R PATEL": 0.0,
  "Himanshu P. Patel": 0.0,
  "PARTH SHAH": 0.0,
  "Rashmi Banerjee": 0.0,
  "SIDHARTH SHAH": 0.0,
  "HITENDRA PATEL": 0.0,
  "JIGNA SHAH": 0.0,
  "MAHESH C. PATEL": 0.0,
  "PARTH DAVE": 0.0,
  "JIGAR PAREKH": 0.0,
  "KUNAL A SHAH D.(ORTHO)": 0.0,
  "D.NB.(ORTHO)": 0.0,
  "MIHIR KARATHIA": 0.0,
  "ESHANYA MULTISPECIALITY HOSPITAL": 0.0,
  "ASHISH PATEL": 0.0,
  "JIGAR SHAH": 0.0,
  "KETAKI ANERAO": 0.0,
  "MALHAR MANIA": 0.0,
  "PREYAS SHAH": 0.0,
  "RAVI GOYAL": 0.0,
  "RAVINA PRADHAN": 0.0,
  "SEJAL MEHTA": 0.0,
  "SHILPI SHUKLA": 0.0,
  "DALITA BHAGADE": 0.0,
  "SONIA DALAL": 0.0,
  "DIPAK SHAH": 0.0,
  "PRATIK DESAI": 0.0,
  "ANNI N.SHAH": 0.0,
  "DEEPAK A BHAVSAR": 0.0,
  "NAYAN SWADIA": 0.0,
  "PRIYANKA IYER M.D. (SKIN & VD)": 0.0,
  "SHAILESH VARU": 0.0,
  "VIVEK AGRAWAL": 0.0,
  "JAYDIP ZALA": 0.0,
  "PRAGNESH C. PATEL": 0.0,
  "TEJASH N VARMA": 0.0,
  "VISHAL CHAUHAN": 0.0,
  "PRANAV VASAVA": 0.0,
  "SANDHYA HARPALE": 0.0,
  "SARBANI RAHA": 0.0,
  "HEMANT RANGWANI": 0.0,
  "CHIRAYU DWIVEDI": 0.0,
  "MANSI BUCH": 0.0,
  "TEJAL VARMA": 0.0,
  "TEJASH SHAH": 0.0,
  "UMANG J BAROT": 0.0,
  "Saurabh Pandya": 0.0,
  "MEHUL H PANDYA": 0.0,
  "NILAM CHOKSHI": 0.0,
  "SANDIP A AKOLKAR": 0.0,
  "SHAILESH A SHAH": 0.0,
  "Rakesh P Prajapati": 0.0,
  "POOJA BELANI  BHAILAL AMIN GENERAL HOSPITAL": 0.0,
  "AADICURA SUPRRSPECIALITY HOSPITAL": 0.0,
  "ANKITA AGRAWAL": 0.0,
  "ARCHANA PATEL": 0.0,
  "ARVIND SHARMA": 0.0,
  "AVINASH GUPTA": 0.0,
  "DARSHIKA R. JADIA": 0.0,
  "DAXESH PATEL": 0.0,
  "DEVANG SHAH": 0.0,
  "PADMA S.IYENGAR": 0.0,
  "GAUTAM KATARIA": 0.0,
  "GIRISH CHIPLUNKAR": 0.0,
  "Harish U Kodnani": 0.0,
  "Hely Prajapati": 0.0,
  "Hemal Dave": 0.0,
  "IRA C. KULKARNI": 0.0,
  "Manish Mittal": 0.0,
  "Mehul Singh": 0.0,
  "Priti Shah": 0.0,
  "NARENDRA PATEL": 0.0,
  "Nirav Modi": 0.0,
  "Sumit Shakya": 0.0,
  "T.G. Sodha": 0.0,
  "Viraj K Patel": 0.0,
  "Yogesh Bhargava": 0.0,
  "Amit Agrawal": 0.0,
  "Bakul D. Prajapati": 0.0,
  "Bipin J. Patel": 0.0,
  "Ashish Kothari": 0.0,
  "Hitesh Rathod": 0.0,
  "Namiisha Patel": 0.0,
  "Dilip S. Nilak": 0.0,
  "Vijay Gupta": 0.0,
  "Ketan Gandhi": 0.0,
  "HIMANSHU AKHANI ( RIDHHI NURSING HOME )": 0.0,
  "Vinay Potbhare": 0.0,
  "MAKARPURA HOSPITAL(UNIT-2)": 0.0
};

var DEFAULT_BRANCH_EXPENSES = window.DEFAULT_BRANCH_EXPENSES = {
  "B": {
    "col_index": 2,
    "branch_name": "7 - Grace Laboratory Gotri",
    "sub_heading": "ongc",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 250.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 18000.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 3200.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 250.0
    },
    "total_monthly_fixed": 21700.0
  },
  "I": {
    "col_index": 9,
    "branch_name": "warasia",
    "sub_heading": "Doc (50%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 0.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 0.0
  },
  "L": {
    "col_index": 12,
    "branch_name": "2 - Grace Laboratory Maneja",
    "sub_heading": "Doc (30%)",
    "expenses": {
      "electricity_bill": 600.0,
      "mobile_recharge": 250.0,
      "internet_recharge": 500.0,
      "rent": 0.0,
      "salary1_phelebo": 20000.0,
      "salary2_logistics": 600.0,
      "maintenance": 0.0,
      "corporation_tax": 400.0,
      "petrol_rapido": 2500.0,
      "biomedical_waste": 730.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 500.0
    },
    "total_monthly_fixed": 26080.0
  },
  "R": {
    "col_index": 18,
    "branch_name": "29- Makarpura Grace laboratory",
    "sub_heading": "Doc (25%)",
    "expenses": {
      "electricity_bill": 5500.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 500.0,
      "rent": 0.0,
      "salary1_phelebo": 12500.0,
      "salary2_logistics": 0.0,
      "maintenance": 1000.0,
      "corporation_tax": 500.0,
      "petrol_rapido": 3700.0,
      "biomedical_waste": 750.0,
      "hand_hygiene": 0.0,
      "cartridge": 330.0,
      "miscellaneous": 1500.0
    },
    "total_monthly_fixed": 26280.0
  },
  "Z": {
    "col_index": 26,
    "branch_name": "ONGC B2B (Makr. Rec)",
    "sub_heading": "ONGC",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 32000.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 32000.0
  },
  "AA": {
    "col_index": 27,
    "branch_name": "Dr.Bhargav Shukla /Dr.Apexa shukla(Makr.  Rec.)",
    "sub_heading": "Doc (40%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 15000.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 3000.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 18000.0
  },
  "AC": {
    "col_index": 29,
    "branch_name": "DR.Chintan Thakkar (Makr. Rec.)",
    "sub_heading": "Doc (40%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 6250.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 700.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 6950.0
  },
  "AE": {
    "col_index": 31,
    "branch_name": "Dr.Sunil Maniyar / Bhavik Thakkar            (Makr. Rec.)",
    "sub_heading": "Doc (35%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 9000.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 1000.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 10000.0
  },
  "AH": {
    "col_index": 34,
    "branch_name": "dr C M kulkarni  / DR. Bhaskar sir     (Makr. Rec.)",
    "sub_heading": "Doc (30%) cm",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 7500.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 7500.0
  },
  "AK": {
    "col_index": 37,
    "branch_name": "3 - Grace Laboratory (dr brijesh patel )",
    "sub_heading": "Doc (50%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 0.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 0.0
  },
  "AM": {
    "col_index": 39,
    "branch_name": "38-DR JIMIT DESAI",
    "sub_heading": "Doc (50%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 6250.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 6250.0
  },
  "AO": {
    "col_index": 41,
    "branch_name": "44 -GRACE LABORATORY  GACL",
    "sub_heading": "Doc (30%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 0.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 0.0
  },
  "AQ": {
    "col_index": 43,
    "branch_name": "makarpura testing unit",
    "sub_heading": "",
    "expenses": {
      "electricity_bill": 30000.0,
      "mobile_recharge": 1200.0,
      "internet_recharge": 1000.0,
      "rent": 36000.0,
      "salary1_phelebo": 153500.0,
      "salary2_logistics": 37500.0,
      "maintenance": 1500.0,
      "corporation_tax": 6000.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 2150.0,
      "hand_hygiene": 0.0,
      "cartridge": 330.0,
      "miscellaneous": 5000.0
    },
    "total_monthly_fixed": 274180.0
  },
  "AS": {
    "col_index": 45,
    "branch_name": "4 - Grace Laboratory (dr viral patel)waghodia",
    "sub_heading": "Doc (30%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 0.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 0.0
  },
  "AU": {
    "col_index": 47,
    "branch_name": "20-SUNNY KHARVA",
    "sub_heading": "Doc (40%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 0.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 0.0
  },
  "AW": {
    "col_index": 49,
    "branch_name": "28-GRACE LABORATORTY (DIVYA LAB)",
    "sub_heading": "b2b rate",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 0.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 0.0
  },
  "AY": {
    "col_index": 51,
    "branch_name": "11 - Grace Laboratory Somatalav",
    "sub_heading": "camp",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 0.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 0.0
  },
  "BA": {
    "col_index": 53,
    "branch_name": "GRACE NIDHI 52",
    "sub_heading": "Doc (45%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 0.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 0.0
  },
  "BF": {
    "col_index": 58,
    "branch_name": "14 - Grace Laboratory DABHOI",
    "sub_heading": "Doc (40%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 300.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 8000.0,
      "salary2_logistics": 105.5,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 0.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 1000.0
    },
    "total_monthly_fixed": 9405.5
  },
  "BH": {
    "col_index": 60,
    "branch_name": "16-DR NITIN SHAH",
    "sub_heading": "Doc (40%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 16500.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 700.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 330.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 17530.0
  },
  "BJ": {
    "col_index": 62,
    "branch_name": "34 -BHUMI HOSPITAL KARELIBAUG",
    "sub_heading": "Doc (25%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 19200.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 3000.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 330.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 22530.0
  },
  "BL": {
    "col_index": 64,
    "branch_name": "5-Grace Laboratory NANAK SIR",
    "sub_heading": "Doc (45%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 15000.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 100.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 330.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 15430.0
  },
  "BO": {
    "col_index": 67,
    "branch_name": "6 - DR HIREN SONI  TARSALI",
    "sub_heading": "ONGC",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 11500.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 400.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 330.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 12230.0
  },
  "BT": {
    "col_index": 72,
    "branch_name": "8 - Grace Laboratory vrundavan",
    "sub_heading": "Doc (25%)",
    "expenses": {
      "electricity_bill": 0.0,
      "mobile_recharge": 0.0,
      "internet_recharge": 0.0,
      "rent": 0.0,
      "salary1_phelebo": 12000.0,
      "salary2_logistics": 0.0,
      "maintenance": 0.0,
      "corporation_tax": 0.0,
      "petrol_rapido": 1700.0,
      "biomedical_waste": 0.0,
      "hand_hygiene": 0.0,
      "cartridge": 0.0,
      "miscellaneous": 0.0
    },
    "total_monthly_fixed": 13700.0
  }
};

var MAKARPURA_SUB_UNITS = window.MAKARPURA_SUB_UNITS = [
  { key: 'ONGC', name: 'ONGC B2B (Makr. Rec)', subHeading: 'ONGC', doctorMatch: ['Dr. ONGC', 'ONGC'], fixedExpenseCol: 'Z', reagentRate: 0.125, stationaryRate: 0.01 },
  { key: 'BHARGAV_SHUKLA', name: 'Dr.Bhargav Shukla /Dr.Apexa shukla(Makr.  Rec.)', subHeading: 'Doc (40%)', doctorMatch: ['Dr. BHARGAV SHUKLA', 'BHARGAV SHUKALA', 'Dr. APEKSHA SHUKALA'], fixedExpenseCol: 'AA', reagentRate: 0.125, stationaryRate: 0.01 },
  { key: 'CHINTAN_THAKKAR', name: 'DR.Chintan Thakkar (Makr. Rec.)', subHeading: 'Doc (40%)', doctorMatch: ['Dr. CHINTAN THAKKAR', 'CHINTAN THAKKAR'], fixedExpenseCol: 'AC', reagentRate: 0.15, stationaryRate: 0.01 },
  { key: 'SUNIL_MANIYAR_BHAVIK', name: 'Dr.Sunil Maniyar / Bhavik Thakkar            (Makr. Rec.)', subHeading: 'Doc (50%)', doctorMatch: ['Dr. BHAVIK THAKKAR', 'BHAVIK THAKKAR', 'Dr. SUNIL MANIYAR'], fixedExpenseCol: 'AE', reagentRate: 0.125, stationaryRate: 0.01 },
  { key: 'KULKARNI_BHASKAR', name: ' dr C M kulkarni  / DR. Bhaskar sir     (Makr. Rec.)', subHeading: 'Doc (30%) cm', doctorMatch: ['Dr. C.M.KULKARNI', 'C.M KULKARNI ', 'Dr. BHASKAR SWAMINATHAN IYER'], fixedExpenseCol: 'AH', reagentRate: 0.125, stationaryRate: 0.01, customCutPct: 30 }
];

var EXPENSE_HEAD_DEFINITIONS = window.EXPENSE_HEAD_DEFINITIONS = [
  { key: 'electricity_bill', label: 'Electricity Bill' },
  { key: 'mobile_recharge', label: 'Mobile Recharge' },
  { key: 'internet_recharge', label: 'Internet Recharge' },
  { key: 'rent', label: 'Rent' },
  { key: 'salary1_phelebo', label: 'Salary 1 (Phlebo)' },
  { key: 'salary2_logistics', label: 'Salary 2 (Logistics / Masi)' },
  { key: 'maintenance', label: 'Maintenance' },
  { key: 'corporation_tax', label: 'Corporation Tax' },
  { key: 'petrol_rapido', label: 'Petrol / Rapido' },
  { key: 'biomedical_waste', label: 'Biomedical Waste' },
  { key: 'hand_hygiene', label: 'Hand Hygiene' },
  { key: 'cartridge', label: 'Cartridge' },
  { key: 'miscellaneous', label: 'Miscellaneous' }
];
